// @ts-check
const eslint = require('@eslint/js');
const tseslint = require('typescript-eslint');
const angular = require('angular-eslint');
const prettier = require('eslint-config-prettier');

module.exports = tseslint.config(
  {
    ignores: [
      'dist/**',
      '.angular/**',
      'coverage/**',
      // Regenerated by `npm run api:sync`; linting it is noise.
      'src/app/core/api/generated/**',
    ],
  },

  // ── TypeScript ──────────────────────────────────────────────────────────────
  {
    files: ['**/*.ts'],
    extends: [
      eslint.configs.recommended,
      ...tseslint.configs.recommended,
      ...tseslint.configs.stylistic,
      ...angular.configs.tsRecommended,
      prettier, // must be last — turns off rules that fight the formatter
    ],
    processor: angular.processInlineTemplates,
    rules: {
      '@angular-eslint/directive-selector': [
        'error',
        { type: 'attribute', prefix: 'z', style: 'camelCase' },
      ],
      '@angular-eslint/component-selector': [
        'error',
        { type: 'element', prefix: 'z', style: 'kebab-case' },
      ],

      // The app is zoneless: change detection is driven by signals, so OnPush is
      // required, not merely preferred. See docs/adr/0005-zoneless-change-detection.md.
      '@angular-eslint/prefer-on-push-component-change-detection': 'error',

      // Standalone is the only supported style here — no NgModules.
      '@angular-eslint/prefer-standalone': 'error',

      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-non-null-assertion': 'error',
      '@typescript-eslint/consistent-type-definitions': ['error', 'interface'],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],

      // ── Layering: features → shared → core, one direction only. ──────────────
      // This boundary erodes silently — one feature-to-feature import always looks
      // harmless, and is never the last one. See ADR-0003.
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/features/*/**'],
              message:
                'Never import across features. Move the shared piece into shared/ (if dumb) or core/ (if stateful). See docs/adr/0003-core-shared-features-layering.md',
            },
            {
              group: ['src/app/core/api/generated/*'],
              message: 'Import generated API types through core/api, not by deep path.',
            },
          ],
        },
      ],
    },
  },

  // core/ and shared/ may not reach upward into features/ at all.
  {
    files: ['src/app/core/**/*.ts', 'src/app/shared/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/features/**'],
              message:
                'core/ and shared/ must not depend on features/. The dependency is backwards — move the logic down a layer.',
            },
          ],
        },
      ],
    },
  },

  // Generated code is regenerated by `npm run api:sync`; linting it is noise.
  {
    files: ['src/app/core/api/generated/**/*.ts'],
    rules: { '@typescript-eslint/no-explicit-any': 'off' },
  },

  // ── Templates ───────────────────────────────────────────────────────────────
  {
    files: ['**/*.html'],
    extends: [
      ...angular.configs.templateRecommended,
      ...angular.configs.templateAccessibility,
    ],
    rules: {
      // Accessibility is review-blocking here, not polish. See docs/accessibility.md.
      '@angular-eslint/template/interactive-supports-focus': 'error',
      '@angular-eslint/template/click-events-have-key-events': 'error',
      '@angular-eslint/template/alt-text': 'error',
      '@angular-eslint/template/label-has-associated-control': 'error',
      '@angular-eslint/template/valid-aria': 'error',

      // Without track, Angular re-creates every DOM node on change and the list flickers.
      '@angular-eslint/template/use-track-by-function': 'error',
    },
  },
);
